title: Anurag Sindhu # your name (or website title) here
logo: "/IMG_20210214_121553 (2).jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ğŸ‘¨â€ğŸ’» Software Engineer  
  <br><br>
  ğŸ“§ <a href="mailto:sindhuanurag2@gmail.com">Connect with me via Email!</a>  
  <br>
  ğŸ”— <a href="https://www.linkedin.com/in/-anurag-sindhu">Visit my LinkedIn Profile</a>  
  <br>
  ğŸ’¼ Let's collaborate and build amazing projects together! ğŸš€  
theme: jekyll-theme-minimal
